#+ endpoint: http://195.251.218.39:8890/sparql
#+ method: GET
#+ summary: test

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>

construct {[] rdfs:label ?l; rdfs:comment ?c}
where {?q a qb:DataSet.
?q rdfs:label ?l. ?q rdfs:comment ?c} 
